import { Col, Row } from "antd";
import Head from "next/head";
import type { ReactNode } from "react";
import styles from "./ContentLayout.module.css";

const ContentLayout = (props: { children: ReactNode }) => {
  const { children } = props;

  return (
    <>
      <Head>
        <title>Movizz</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Row>
        <Col xs={24}>
          <div className={styles.main}>
            <div className={styles.container}>{children}</div>
          </div>
        </Col>
      </Row>
    </>
  );
};

export default ContentLayout;
